/*
 * This file was automatically generated by EvoSuite
 * Sat May 20 20:34:37 GMT 2023
 */

package org.apache.commons.fileupload2;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.fileupload2.FileItemFactory;
import org.apache.commons.fileupload2.FileUpload;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FileUpload_ESTest extends FileUpload_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FileUpload fileUpload0 = new FileUpload();
      assertEquals((-1L), fileUpload0.getFileCountMax());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FileUpload fileUpload0 = new FileUpload((FileItemFactory) null);
      FileItemFactory fileItemFactory0 = fileUpload0.getFileItemFactory();
      assertNull(fileItemFactory0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FileUpload fileUpload0 = new FileUpload((FileItemFactory) null);
      fileUpload0.setFileItemFactory((FileItemFactory) null);
      assertNull(fileUpload0.getHeaderEncoding());
  }
}
