/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat May 20 20:34:37 GMT 2023
 */

package org.apache.commons.fileupload2;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class FileUpload_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.fileupload2.FileUpload"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\MTAIMO~1\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.dir", "C:\\evosuite"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(FileUpload_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.fileupload2.util.FileItemHeadersImpl",
      "org.apache.commons.fileupload2.pub.FileUploadSizeException",
      "org.apache.commons.fileupload2.FileItemIterator",
      "org.apache.commons.fileupload2.pub.FileUploadFileCountLimitException",
      "org.apache.commons.fileupload2.AbstractFileUpload",
      "org.apache.commons.fileupload2.FileItemHeaders",
      "org.apache.commons.fileupload2.FileItemFactory",
      "org.apache.commons.fileupload2.RequestContext",
      "org.apache.commons.fileupload2.FileItem",
      "org.apache.commons.fileupload2.FileUpload",
      "org.apache.commons.fileupload2.FileItemHeadersSupport",
      "org.apache.commons.fileupload2.ProgressListener",
      "org.apache.commons.fileupload2.FileUploadException"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(FileUpload_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.fileupload2.AbstractFileUpload",
      "org.apache.commons.fileupload2.FileUpload",
      "org.apache.commons.fileupload2.util.FileItemHeadersImpl",
      "org.apache.commons.fileupload2.disk.DiskFileItemFactory",
      "org.apache.commons.fileupload2.impl.FileItemIteratorImpl",
      "org.apache.commons.fileupload2.ParameterParser",
      "org.apache.commons.fileupload2.FileUploadException",
      "org.apache.commons.fileupload2.pub.FileUploadContentTypeException",
      "org.apache.commons.fileupload2.util.mime.RFC2231Utility",
      "org.apache.commons.fileupload2.util.mime.MimeUtility"
    );
  }
}
